from models import StudyNotes, WorkBrief, VideoInsights
from typing import Union
import re
from datetime import datetime


def sanitize_filename(title: str) -> str:
    clean = re.sub(r'[^\w\s-]', '', title)
    clean = re.sub(r'\s+', '-', clean.strip())
    return clean[:60].lower()


def study_notes_to_markdown(notes: StudyNotes, source_url: str = "") -> str:
    date = datetime.now().strftime("%Y-%m-%d")
    lines = []

    lines.append(f"# 📚 {notes.title}\n")
    lines.append(f"> {notes.core_concept}\n")

    if notes.formula_sheet:
        lines.append("## Formula Sheet\n")
        lines.append("```")
        for formula in notes.formula_sheet:
            lines.append(formula)
        lines.append("```\n")

    if notes.key_facts:
        lines.append("## Key Facts\n")
        for i, fact in enumerate(notes.key_facts, 1):
            lines.append(f"{i}. {fact}")
        lines.append("")

    if notes.common_mistakes:
        lines.append("## Common Mistakes\n")
        for mistake in notes.common_mistakes:
            lines.append(f"- {mistake}")
        lines.append("")

    if notes.self_test:
        lines.append("## Self-Test Questions\n")
        for i, question in enumerate(notes.self_test, 1):
            lines.append(f"{i}. {question}")
        lines.append("")

    if notes.prerequisites:
        lines.append("## Prerequisites\n")
        for prereq in notes.prerequisites:
            lines.append(f"- {prereq}")
        lines.append("")

    if notes.further_reading:
        lines.append("## Further Reading\n")
        for topic in notes.further_reading:
            lines.append(f"- {topic}")
        lines.append("")

    lines.append("---")
    if source_url:
        lines.append(f"*Generated by NotionClip on {date} from: {source_url}*")
    else:
        lines.append(f"*Generated by NotionClip on {date}*")

    return "\n".join(lines)


def work_brief_to_markdown(brief: WorkBrief, source_url: str = "") -> str:
    date = datetime.now().strftime("%Y-%m-%d")
    lines = []

    lines.append(f"# 💼 {brief.title}\n")
    lines.append(f"**{brief.recommendation}**\n")
    lines.append(f"> {brief.one_liner}\n")

    if brief.key_points:
        lines.append("## Key Points\n")
        for point in brief.key_points:
            lines.append(f"- {point}")
        lines.append("")

    if brief.tools_mentioned:
        lines.append("## Tools Mentioned\n")
        tools_inline = " ".join([f"`{tool}`" for tool in brief.tools_mentioned])
        lines.append(tools_inline)
        lines.append("")

    if brief.decisions_to_make:
        lines.append("## Decisions to Make\n")
        for decision in brief.decisions_to_make:
            lines.append(f"- [ ] {decision}")
        lines.append("")

    if brief.next_actions:
        lines.append("## Next Actions\n")
        for action in brief.next_actions:
            lines.append(f"- [ ] {action}")
        lines.append("")

    lines.append("---")
    if source_url:
        lines.append(f"*Generated by NotionClip on {date} from: {source_url}*")
    else:
        lines.append(f"*Generated by NotionClip on {date}*")

    return "\n".join(lines)


def quick_insights_to_markdown(insights: VideoInsights, source_url: str = "") -> str:
    date = datetime.now().strftime("%Y-%m-%d")
    lines = []

    lines.append(f"# ⚡ {insights.title}\n")

    if hasattr(insights, 'summary') and insights.summary:
        lines.append(f"> {insights.summary}\n")

    if hasattr(insights, 'key_takeaways') and insights.key_takeaways:
        lines.append("## Key Takeaways\n")
        for item in insights.key_takeaways:
            lines.append(f"- {item}")
        lines.append("")

    if hasattr(insights, 'topics') and insights.topics:
        lines.append("## Topics Covered\n")
        for topic in insights.topics:
            lines.append(f"- {topic}")
        lines.append("")

    if hasattr(insights, 'action_items') and insights.action_items:
        lines.append("## Action Items\n")
        for action in insights.action_items:
            lines.append(f"- [ ] {action}")
        lines.append("")

    lines.append("---")
    if source_url:
        lines.append(f"*Generated by NotionClip on {date} from: {source_url}*")
    else:
        lines.append(f"*Generated by NotionClip on {date}*")

    return "\n".join(lines)


def insights_to_markdown(
    insights: Union[StudyNotes, WorkBrief, VideoInsights],
    source_url: str = ""
) -> tuple[str, str]:
    """
    Returns (markdown_content, suggested_filename)
    Auto-detects model type.
    """
    if isinstance(insights, StudyNotes):
        md = study_notes_to_markdown(insights, source_url)
        filename = f"notionclip-study-{sanitize_filename(insights.title)}.md"
    elif isinstance(insights, WorkBrief):
        md = work_brief_to_markdown(insights, source_url)
        filename = f"notionclip-work-{sanitize_filename(insights.title)}.md"
    else:
        md = quick_insights_to_markdown(insights, source_url)
        filename = f"notionclip-quick-{sanitize_filename(insights.title)}.md"

    return md, filename