"use client"

import { useState } from "react"
import { Insights, Mode, StudyInsights, WorkInsights, QuickInsights } from "@/lib/types"

interface ExportButtonsProps {
  results: Insights | null
  sourceUrl?: string
  mode: Mode
}

type ExportFormat = "markdown" | "plain" | "html"

// Export format converters
function generateMarkdown(results: Insights, sourceUrl: string, mode: Mode): { content: string; filename: string } {
  const date = new Date().toISOString().split('T')[0]
  let content = ""
  let filename = ""

  if (mode === "study") {
    const data = results as StudyInsights
    content = `# 📚 ${data.title || "Study Notes"}\n\n`
    content += `> **Core Concept:** ${data.core_concept || "N/A"}\n\n`

    if (data.formula_sheet?.length) {
      content += `## Formula Sheet\n\`\`\`\n${data.formula_sheet.join('\n')}\n\`\`\`\n\n`
    }

    if (data.key_facts?.length) {
      content += `## Key Facts\n${data.key_facts.map((f, i) => `${i + 1}. ${f}`).join('\n')}\n\n`
    }

    if (data.common_mistakes?.length) {
      content += `## Common Mistakes\n${data.common_mistakes.map(m => `- ${m}`).join('\n')}\n\n`
    }

    if (data.self_test?.length) {
      content += `## Self-Test Questions\n${data.self_test.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\n`
    }

    if (data.prerequisites?.length) {
      content += `## Prerequisites\n${data.prerequisites.map(p => `- ${p}`).join('\n')}\n\n`
    }

    if (data.further_reading?.length) {
      content += `## Further Reading\n${data.further_reading.map(r => `- ${r}`).join('\n')}\n\n`
    }

    filename = `notionclip-study-${sanitizeFilename(data.title || "notes")}.md`
  } else if (mode === "work") {
    const data = results as WorkInsights
    content = `# 💼 ${data.title || "Work Brief"}\n\n`
    content += `**${data.recommendation?.split(' — ')[0] || "Watch"}**\n\n`
    content += `> ${data.one_liner || "N/A"}\n\n`

    if (data.key_points?.length) {
      content += `## Key Points\n${data.key_points.map(p => `- ${p}`).join('\n')}\n\n`
    }

    if (data.tools_mentioned?.length) {
      content += `## Tools Mentioned\n${data.tools_mentioned.map(t => `\`${t}\``).join(', ')}\n\n`
    }

    if (data.decisions_to_make?.length) {
      content += `## Decisions to Make\n${data.decisions_to_make.map(d => `- [ ] ${d}`).join('\n')}\n\n`
    }

    if (data.next_actions?.length) {
      content += `## Next Actions\n${data.next_actions.map(a => `- [ ] ${a}`).join('\n')}\n\n`
    }

    filename = `notionclip-work-${sanitizeFilename(data.title || "brief")}.md`
  } else {
    const data = results as QuickInsights
    content = `# ⚡ ${data.title || "Quick Summary"}\n\n`
    content += `> ${data.summary || "N/A"}\n\n`

    if (data.key_takeaways?.length) {
      content += `## Key Takeaways\n${data.key_takeaways.map(t => `- ${t}`).join('\n')}\n\n`
    }

    if (data.topics_covered?.length) {
      content += `## Topics Covered\n${data.topics_covered.map(t => `- ${t}`).join('\n')}\n\n`
    }

    if (data.action_items?.length) {
      content += `## Action Items\n${data.action_items.map(a => `- [ ] ${a}`).join('\n')}\n\n`
    }

    filename = `notionclip-quick-${sanitizeFilename(data.title || "summary")}.md`
  }

  content += `---\n*Generated by NotionClip on ${date}*`
  if (sourceUrl) content += ` from: ${sourceUrl}`

  return { content, filename }
}

function generatePlainText(results: Insights, sourceUrl: string, mode: Mode): { content: string; filename: string } {
  const date = new Date().toISOString().split('T')[0]
  let content = ""
  let filename = ""

  if (mode === "study") {
    const data = results as StudyInsights
    content = `${data.title || "STUDY NOTES"}\n${"=".repeat((data.title || "STUDY NOTES").length)}\n\n`
    content += `CORE CONCEPT\n${"-".repeat(12)}\n${data.core_concept || "N/A"}\n\n`

    if (data.formula_sheet?.length) {
      content += `FORMULA SHEET\n${"-".repeat(14)}\n${data.formula_sheet.join('\n')}\n\n`
    }

    if (data.key_facts?.length) {
      content += `KEY FACTS\n${"-".repeat(9)}\n${data.key_facts.map((f, i) => `${i + 1}. ${f}`).join('\n')}\n\n`
    }

    if (data.common_mistakes?.length) {
      content += `COMMON MISTAKES\n${"-".repeat(15)}\n${data.common_mistakes.map(m => `• ${m}`).join('\n')}\n\n`
    }

    if (data.self_test?.length) {
      content += `SELF-TEST QUESTIONS\n${"-".repeat(18)}\n${data.self_test.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\n`
    }

    if (data.prerequisites?.length) {
      content += `PREREQUISITES\n${"-".repeat(12)}\n${data.prerequisites.map(p => `• ${p}`).join('\n')}\n\n`
    }

    if (data.further_reading?.length) {
      content += `FURTHER READING\n${"-".repeat(15)}\n${data.further_reading.map(r => `• ${r}`).join('\n')}\n\n`
    }

    filename = `notionclip-study-${sanitizeFilename(data.title || "notes")}.txt`
  } else if (mode === "work") {
    const data = results as WorkInsights
    content = `${data.title || "WORK BRIEF"}\n${"=".repeat((data.title || "WORK BRIEF").length)}\n\n`
    content += `RECOMMENDATION: ${data.recommendation?.split(' — ')[0] || "WATCH"}\n${"-".repeat(15)}\n${data.recommendation || "N/A"}\n\n`
    content += `ONE-LINER\n${"-".repeat(9)}\n${data.one_liner || "N/A"}\n\n`

    if (data.key_points?.length) {
      content += `KEY POINTS\n${"-".repeat(10)}\n${data.key_points.map(p => `• ${p}`).join('\n')}\n\n`
    }

    if (data.tools_mentioned?.length) {
      content += `TOOLS: ${data.tools_mentioned.join(', ')}\n\n`
    }

    if (data.decisions_to_make?.length) {
      content += `DECISIONS TO MAKE\n${"-".repeat(16)}\n${data.decisions_to_make.map(d => `[ ] ${d}`).join('\n')}\n\n`
    }

    if (data.next_actions?.length) {
      content += `NEXT ACTIONS\n${"-".repeat(12)}\n${data.next_actions.map(a => `[ ] ${a}`).join('\n')}\n\n`
    }

    filename = `notionclip-work-${sanitizeFilename(data.title || "brief")}.txt`
  } else {
    const data = results as QuickInsights
    content = `${data.title || "QUICK SUMMARY"}\n${"=".repeat((data.title || "QUICK SUMMARY").length)}\n\n`
    content += `${data.summary || "N/A"}\n\n`

    if (data.key_takeaways?.length) {
      content += `KEY TAKEAWAYS\n${"-".repeat(13)}\n${data.key_takeaways.map(t => `• ${t}`).join('\n')}\n\n`
    }

    if (data.topics_covered?.length) {
      content += `TOPICS COVERED\n${"-".repeat(13)}\n${data.topics_covered.map(t => `• ${t}`).join('\n')}\n\n`
    }

    if (data.action_items?.length) {
      content += `ACTION ITEMS\n${"-".repeat(12)}\n${data.action_items.map(a => `[ ] ${a}`).join('\n')}\n\n`
    }

    filename = `notionclip-quick-${sanitizeFilename(data.title || "summary")}.txt`
  }

  content += `Generated by NotionClip on ${date}`
  if (sourceUrl) content += ` from: ${sourceUrl}`

  return { content, filename }
}

function generateHTML(results: Insights, sourceUrl: string, mode: Mode): { content: string; filename: string } {
  const date = new Date().toISOString().split('T')[0]
  let title = ""
  let htmlContent = ""
  let filename = ""

  if (mode === "study") {
    const data = results as StudyInsights
    title = data.title || "Study Notes"
    htmlContent = `<h1>📚 ${title}</h1>`
    htmlContent += `<blockquote><strong>Core Concept:</strong> ${data.core_concept || "N/A"}</blockquote>`

    if (data.formula_sheet?.length) {
      htmlContent += `<h2>Formula Sheet</h2><pre>${data.formula_sheet.join('\n')}</pre>`
    }

    if (data.key_facts?.length) {
      htmlContent += `<h2>Key Facts</h2><ol>${data.key_facts.map(f => `<li>${f}</li>`).join('')}</ol>`
    }

    if (data.common_mistakes?.length) {
      htmlContent += `<h2>Common Mistakes</h2><ul>${data.common_mistakes.map(m => `<li>${m}</li>`).join('')}</ul>`
    }

    if (data.self_test?.length) {
      htmlContent += `<h2>Self-Test Questions</h2><ol>${data.self_test.map(q => `<li>${q}</li>`).join('')}</ol>`
    }

    if (data.prerequisites?.length) {
      htmlContent += `<h2>Prerequisites</h2><ul>${data.prerequisites.map(p => `<li>${p}</li>`).join('')}</ul>`
    }

    if (data.further_reading?.length) {
      htmlContent += `<h2>Further Reading</h2><ul>${data.further_reading.map(r => `<li>${r}</li>`).join('')}</ul>`
    }

    filename = `notionclip-study-${sanitizeFilename(data.title || "notes")}.html`
  } else if (mode === "work") {
    const data = results as WorkInsights
    title = data.title || "Work Brief"
    htmlContent = `<h1>💼 ${title}</h1>`
    htmlContent += `<p><strong>${data.recommendation?.split(' — ')[0] || "Watch"}</strong></p>`
    htmlContent += `<blockquote>${data.one_liner || "N/A"}</blockquote>`

    if (data.key_points?.length) {
      htmlContent += `<h2>Key Points</h2><ul>${data.key_points.map(p => `<li>${p}</li>`).join('')}</ul>`
    }

    if (data.tools_mentioned?.length) {
      htmlContent += `<h2>Tools Mentioned</h2><p>${data.tools_mentioned.map(t => `<code>${t}</code>`).join(', ')}</p>`
    }

    if (data.decisions_to_make?.length) {
      htmlContent += `<h2>Decisions to Make</h2><ul>${data.decisions_to_make.map(d => `<li><input type="checkbox" /> ${d}</li>`).join('')}</ul>`
    }

    if (data.next_actions?.length) {
      htmlContent += `<h2>Next Actions</h2><ul>${data.next_actions.map(a => `<li><input type="checkbox" /> ${a}</li>`).join('')}</ul>`
    }

    filename = `notionclip-work-${sanitizeFilename(data.title || "brief")}.html`
  } else {
    const data = results as QuickInsights
    title = data.title || "Quick Summary"
    htmlContent = `<h1>⚡ ${title}</h1>`
    htmlContent += `<blockquote>${data.summary || "N/A"}</blockquote>`

    if (data.key_takeaways?.length) {
      htmlContent += `<h2>Key Takeaways</h2><ul>${data.key_takeaways.map(t => `<li>${t}</li>`).join('')}</ul>`
    }

    if (data.topics_covered?.length) {
      htmlContent += `<h2>Topics Covered</h2><ul>${data.topics_covered.map(t => `<li>${t}</li>`).join('')}</ul>`
    }

    if (data.action_items?.length) {
      htmlContent += `<h2>Action Items</h2><ul>${data.action_items.map(a => `<li><input type="checkbox" /> ${a}</li>`).join('')}</ul>`
    }

    filename = `notionclip-quick-${sanitizeFilename(data.title || "summary")}.html`
  }

  const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 20px; }
    h1, h2 { color: #1a1a1a; margin-top: 1.5em; }
    h1 { border-bottom: 3px solid #007bff; padding-bottom: 10px; }
    blockquote { border-left: 4px solid #007bff; padding-left: 1em; margin: 1em 0; color: #666; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: 'Courier New', monospace; }
    pre { background: #f4f4f4; padding: 1em; border-radius: 5px; overflow-x: auto; }
    ul, ol { margin: 1em 0; padding-left: 2em; }
    li { margin: 0.5em 0; }
    input[type="checkbox"] { margin-right: 0.5em; }
    footer { margin-top: 2em; padding-top: 1em; border-top: 1px solid #ddd; font-size: 0.9em; color: #999; }
  </style>
</head>
<body>
  ${htmlContent}
  <footer>Generated by NotionClip on ${date}${sourceUrl ? ` from: ${sourceUrl}` : ""}</footer>
</body>
</html>`

  return { content: fullHTML, filename }
}

function sanitizeFilename(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 60)
}

export default function ExportButtons({
  results,
  sourceUrl = "",
  mode,
}: ExportButtonsProps) {
  const [exportState, setExportState] = useState<Record<ExportFormat, "idle" | "loading" | "copied" | "error">>({
    markdown: "idle",
    plain: "idle",
    html: "idle",
  })
  const [downloadState, setDownloadState] = useState<Record<ExportFormat, "idle" | "loading" | "done" | "error">>({
    markdown: "idle",
    plain: "idle",
    html: "idle",
  })
  const [fallbackContent, setFallbackContent] = useState<{ format: ExportFormat; content: string } | null>(null)

  if (!results) {
    return (
      <div className="text-center text-white/50 text-sm py-4">
        Process content first to enable export
      </div>
    )
  }

  async function handleCopy(format: ExportFormat) {
    setExportState(prev => ({ ...prev, [format]: "loading" }))
    try {
      let exported
      if (format === "markdown") {
        exported = generateMarkdown(results!, sourceUrl, mode)
      } else if (format === "plain") {
        exported = generatePlainText(results!, sourceUrl, mode)
      } else {
        exported = generateHTML(results!, sourceUrl, mode)
      }

      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(exported.content)
        setExportState(prev => ({ ...prev, [format]: "copied" }))
        setTimeout(() => setExportState(prev => ({ ...prev, [format]: "idle" })), 2000)
      } else {
        setFallbackContent({ format, content: exported.content })
        setExportState(prev => ({ ...prev, [format]: "idle" }))
      }
    } catch {
      setExportState(prev => ({ ...prev, [format]: "error" }))
      setTimeout(() => setExportState(prev => ({ ...prev, [format]: "idle" })), 2000)
    }
  }

  async function handleDownload(format: ExportFormat) {
    setDownloadState(prev => ({ ...prev, [format]: "loading" }))
    try {
      let exported
      if (format === "markdown") {
        exported = generateMarkdown(results!, sourceUrl, mode)
      } else if (format === "plain") {
        exported = generatePlainText(results!, sourceUrl, mode)
      } else {
        exported = generateHTML(results!, sourceUrl, mode)
      }

      const mimeType = format === "markdown" ? "text/markdown" : format === "plain" ? "text/plain" : "text/html"
      const blob = new Blob([exported.content], { type: `${mimeType};charset=utf-8` })
      const url = URL.createObjectURL(blob)
      const link = document.createElement("a")
      link.href = url
      link.download = exported.filename
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)

      setDownloadState(prev => ({ ...prev, [format]: "done" }))
      setTimeout(() => setDownloadState(prev => ({ ...prev, [format]: "idle" })), 2000)
    } catch {
      setDownloadState(prev => ({ ...prev, [format]: "error" }))
      setTimeout(() => setDownloadState(prev => ({ ...prev, [format]: "idle" })), 2000)
    }
  }

  const formats: Array<{ format: ExportFormat; label: string; icon: string; mimeHint: string }> = [
    { format: "markdown", label: "Copy as Markdown", icon: "📋", mimeHint: ".md" },
    { format: "plain", label: "Copy as Text", icon: "📄", mimeHint: ".txt" },
    { format: "html", label: "Copy as HTML", icon: "🌐", mimeHint: ".html" },
  ]

  return (
    <div className="flex flex-col gap-4 w-full">
      <div className="grid grid-cols-3 gap-2">
        {formats.map(({ format, label, icon, mimeHint }) => (
          <div key={format} className="flex flex-col gap-1">
            {/* Copy button */}
            <button
              onClick={() => handleCopy(format)}
              disabled={exportState[format] === "loading"}
              className="flex items-center justify-center gap-2 px-2 py-2 text-xs
                         border border-gray-600 rounded-lg
                         text-gray-300 hover:bg-gray-800
                         disabled:opacity-50 disabled:cursor-not-allowed
                         transition-colors duration-150"
              title={label}
            >
              {exportState[format] === "loading" && (
                <span className="animate-spin text-xs">⟳</span>
              )}
              {exportState[format] === "copied" && <span className="text-green-400">✓</span>}
              {exportState[format] === "error" && <span className="text-red-400">✗</span>}
              {exportState[format] === "idle" && <span>{icon}</span>}

              <span className="text-xs">
                {exportState[format] === "loading" && "..."}
                {exportState[format] === "copied" && "Copied!"}
                {exportState[format] === "error" && "Failed"}
                {exportState[format] === "idle" && "Copy"}
              </span>
            </button>

            {/* Download button */}
            <button
              onClick={() => handleDownload(format)}
              disabled={downloadState[format] === "loading"}
              className="flex items-center justify-center gap-1 px-2 py-1 text-xs
                         border border-gray-600 rounded-lg
                         text-gray-300 hover:bg-gray-800
                         disabled:opacity-50 disabled:cursor-not-allowed
                         transition-colors duration-150"
              title={`Download as ${mimeHint}`}
            >
              {downloadState[format] === "loading" && (
                <span className="animate-spin text-xs">⟳</span>
              )}
              {downloadState[format] === "done" && (
                <span className="text-green-400">✓</span>
              )}
              {downloadState[format] === "error" && (
                <span className="text-red-400">✗</span>
              )}
              {downloadState[format] === "idle" && <span>⬇</span>}

              <span className="text-xs">
                {downloadState[format] === "loading" && "..."}
                {downloadState[format] === "done" && "Done"}
                {downloadState[format] === "error" && "Failed"}
                {downloadState[format] === "idle" && mimeHint}
              </span>
            </button>
          </div>
        ))}
      </div>

      {/* Clipboard fallback — shown if clipboard API unavailable */}
      {fallbackContent && (
        <div className="mt-2 p-3 bg-gray-900 border border-gray-700 rounded-lg">
          <div className="flex justify-between items-center mb-2">
            <span className="text-xs text-gray-400">
              Select all and copy manually (Ctrl+A, Ctrl+C)
            </span>
            <button
              onClick={() => setFallbackContent(null)}
              className="text-xs text-gray-500 hover:text-gray-300"
            >
              ✕ Close
            </button>
          </div>
          <textarea
            readOnly
            value={fallbackContent.content}
            onClick={(e) => (e.target as HTMLTextAreaElement).select()}
            className="w-full h-48 text-xs font-mono bg-gray-950
                       text-gray-300 border border-gray-700 rounded
                       p-2 resize-none focus:outline-none"
          />
        </div>
      )}
    </div>
  )
}